services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: xxx.xxx.xxx.xxx:xxxx         # Use port number if not 3306
      WORDPRESS_DB_USER: db_user
      WORDPRESS_DB_PASSWORD: db_pass
      WORDPRESS_DB_NAME: db_name
    volumes:
      - ./wordpress:/var/www/html
